In [1]:
import numpy as np 

## Populate arrays with specific numbers 

In [2]:
# array
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


In [3]:
two_dimensional_array = np.array([[6, 5], [11, 7], [4, 8]])
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


##  Populate arrays with sequences of numbers

In [4]:
# arange
sequence_of_integers = np.arange(5, 12) # alt sınır 5, üst sınır 12 içermeyen bir dizi oluşturuldu.
print(sequence_of_integers)

[ 5  6  7  8  9 10 11]


## Populate arrays with random numbers 

In [5]:
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(6))
# 50 ile 100 arasında rastgele tam sayılarla 6 elemanlı dizi oluşturuldu.
print(random_integers_between_50_and_100)

[70 69 69 73 53 94]


In [6]:
random_floats_between_0_and_1 = np.random.random([6])
# 0.0 ile 1.0 arasında rastgele float nokta değerleri oluşturuldu.
print(random_floats_between_0_and_1)

[0.79490337 0.89819278 0.30976858 0.92510994 0.38353275 0.30414556]


## Mathematical Operations on NumPy Operands 

#### Broadcasting 

In [7]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)

[2.79490337 2.89819278 2.30976858 2.92510994 2.38353275 2.30414556]


In [8]:
random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_and_300)

[210 207 207 219 159 282]


## Task 1: Create a Linear Dataset 

In [9]:
feature = np.arange(6, 21) # 6 ile 20 arasında bir tam sayı dizisi oluşturuldu
print(feature)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [10]:
label = (feature * 3) + 4  # oluşturulan dizi elemanlarına 15 eklendi
print(label)

[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


## Task 2: Add Some Noise to the Dataset 

In [11]:
noise = (np.random.random([15]) * 4 ) - 2 # -2 ve +2 tam sayıları arasında random float sayı dizisi oluşturuldu
print(noise)

[-1.40971424 -1.83000668 -1.22782808  0.78210275  0.70795394 -0.20699605
 -1.89487982 -0.02393122 -1.56046271  0.63575982 -1.33091605  0.43320435
 -0.65372345  0.68911343  0.3006363 ]


In [12]:
label = label + noise
print(label)  # label dizi elemanlarına eklendi

[20.59028576 23.16999332 26.77217192 31.78210275 34.70795394 36.79300395
 38.10512018 42.97606878 44.43953729 49.63575982 50.66908395 55.43320435
 57.34627655 61.68911343 64.3006363 ]
