In [1]:
import numpy as np
import pandas as pd

## Creating a DataFrame 

In [2]:
my_data = np.array([[0, 3], [10, 7], [20, 9], [30, 14], [40, 15]]) # numpy kütüphanesi ile 5x2 boyutunda dizi oluşturuldu
my_column_names = ['temperature', 'activity'] # sütun isimleri verildi
my_dataframe = pd.DataFrame(data=my_data, columns=my_column_names) # dataFrame oluşturuldu
print(my_dataframe)

   temperature  activity
0            0         3
1           10         7
2           20         9
3           30        14
4           40        15


## Adding aa new column to a DataFrame 

In [3]:
my_dataframe["adjusted"] = my_dataframe["activity"] + 2 # yeni sütun ismi ve verileri oluşturuldu
print(my_dataframe)

   temperature  activity  adjusted
0            0         3         5
1           10         7         9
2           20         9        11
3           30        14        16
4           40        15        17


## Specifying a subset of a DataFrame 

In [4]:
print("Rows #0, #1 and #2:" '\n') 
print(my_dataframe.head(3), '\n')# ilk 3 satır 

Rows #0, #1 and #2:

   temperature  activity  adjusted
0            0         3         5
1           10         7         9
2           20         9        11 



In [5]:
print("Row #2:" '\n')
print(my_dataframe.iloc[[2]], '\n') #indekslenen satır

Row #2:

   temperature  activity  adjusted
2           20         9        11 



In [6]:
print("Rows #1, #2, and #3:" '\n')
print(my_dataframe[1:4], '\n') # 1 ve 4-1 arası satırlar

Rows #1, #2, and #3:

   temperature  activity  adjusted
1           10         7         9
2           20         9        11
3           30        14        16 



In [7]:
print("Column 'temperature':" 'n')
print(my_dataframe['temperature']) # temperature sütunu

Column 'temperature':n
0     0
1    10
2    20
3    30
4    40
Name: temperature, dtype: int32


## Task 1: Create a DataFrame 

In [8]:
task_data = np.random.randint(low=0, high=101, size=(3, 4)) # 1 ile 100 arasında 12 adet integer random veri oluşturuldu
print(task_data)

[[ 5 28 73 75]
 [48 49 99 91]
 [18 65 10 63]]


In [9]:
task_column_names = ['Eleanor','Chidi', 'Tahani', 'Jason'] # sütun isimleri verildi
print(task_column_names)

['Eleanor', 'Chidi', 'Tahani', 'Jason']


In [10]:
task_dataframe = pd.DataFrame(data=task_data, columns=task_column_names) # dataframe oluşturuldu
print(task_dataframe)

   Eleanor  Chidi  Tahani  Jason
0        5     28      73     75
1       48     49      99     91
2       18     65      10     63


In [11]:
# the value in the cell of row #1 of the Eleanor column
task_dataframe.Eleanor[1]  #Eleanor sütununun 1. indeksi

48

In [12]:
# Create a fifth column named Janet, which is populated with the row-by-row sums of Tahani and Jason
task_dataframe["Janet"] = task_dataframe["Tahani"] + task_dataframe["Jason"]
print(task_dataframe)

   Eleanor  Chidi  Tahani  Jason  Janet
0        5     28      73     75    148
1       48     49      99     91    190
2       18     65      10     63     73


## Copying a DataFrame 

In [13]:
reference_to_df = task_dataframe # task_dataframe, yeni bir değişkene atarak referans oluşturuldu

In [14]:
print("Starting value of task_dataframe: %d" % task_dataframe['Jason'][1])
print("Starting value of reference_to_df: %d" % reference_to_df['Jason'][1])

Starting value of task_dataframe: 91
Starting value of reference_to_df: 91


In [15]:
task_dataframe.at[1, 'Jason'] = task_dataframe['Jason'][1] + 5
print("Updated task_dataframe: %d" % task_dataframe['Jason'][1])
print("Updated reference_to_df: %d\n\n" % reference_to_df['Jason'][1])

Updated task_dataframe: 96
Updated reference_to_df: 96




In [16]:
copy_of_my_dataframe = my_dataframe.copy() # my_dataframe, yeni bir değişkene copy methoduyla kopyalandı

In [17]:
print("Starting value of my_dataframe: %d" % my_dataframe['activity'][1])
print("Starting value of copy_of_my_dataframe: %d\n" % copy_of_my_dataframe['activity'][1])

Starting value of my_dataframe: 7
Starting value of copy_of_my_dataframe: 7



In [18]:
my_dataframe.at[1, 'activity'] = my_dataframe['activity'][1] + 3
print("Updated my_dataframe: %d" % my_dataframe['activity'][1])
print("copy_of_my_dataframe does not get updated: %d" % copy_of_my_dataframe['activity'][1])

Updated my_dataframe: 10
copy_of_my_dataframe does not get updated: 7
